error = "red"
comment = "comment"
constant = "purple"
function = "green"
keyword = "pink"
type = { fg = "cyan", modifiers = ["italic"] }
string = "yellow"
variable = "foreground"
property = "foreground"
"function.builtin" = "cyan"
"ui.background" = { bg = "background" }
"ui.text" =  { fg = "foreground" }
"ui.statusLine" = { fg = "foreground", bg = "color0" } 
"ui.statusLine.inactive" = { fg = "foreground", bg = "color0" }
"ui.selection" = { bg = "selection" }
"ui.info" = { fg = "foreground", bg = "color0" }
"ui.menu" = { fg = "foreground", bg = "color0" }
"ui.window" = { fg = "foreground", bg = "color0" }
"ui.help" = { fg = "foreground", bg = "color0" }
"ui.linenr" = "comment"
"ui.linenr.selected" = "foreground"
"ui.menu.selected" = { fg =  "foreground", bg = "color0" }
number = "purple"
attribute = "green"
"constant.builtin" = "purple"
"ui.popup" = { fg =  "foreground", bg = "color0" }

namespace = "pink"

[palette]
background = "#f8f8f2"
foreground = "#282a36"
selection = "#cbcee5"
comment = "#6272A4"
red = "#d82f39"
orange = "#a0651b"
yellow = "#4c5b00"
green = "#008525"
purple = "#855fbf"
cyan = "#8BE9FD"
pink = "#c13f8e"
white = "#727272"
color0 = "#eaebf9"